name: CI/CD

on:
  # Trigger the workflow on push,
  # but only for the main branch
  push:
    branches:
      - main

jobs:
  build_deploy_aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Get yarn cache directory
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Retrieve cached yarn-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Run jest unit tests in TypeScript folder
        run: npm run test:jest
        working-directory: ./TypeScript
